### ISSUE TITLE
M.2 thunderbolt enclosure PCIe/NVMe clarification

### ISSUE THREAD

**Issue by huettern** [SMB784/SQRL_quickstart#2]
I came across your repo when looking for M.2 enclosures compatible with the LitePCI core. From the pictures I can see you are using a `Avolusion SSDTB900-PRO` enclosure and you mention that it should work with any JHL6340/JHL7540 chip. In the same paragraph you list the `ORICO M2V01-C4` as a possible alternative. It houses a JMS583 afaik which is a simple USB3.1 <-> NVMe bridge supporting ` USB  Mass  Storage  Class  Bulk-Only Transport  (BOT)  and  USB  Attached  SCSI  Protocol  (UASP)` [1]

From your twitter post [2](2) I can see that the FPGA is connected through a JHL6540 to your host controller (again, JHL6540). How can you be certain that a JMS583 would work as well? It wouldn't expose the "raw" PCIe endpoint to your host.

[1]: https://www.jmicron.com/file/download/1012/JMS583_Product+Brief.pdf
[2]: https://twitter.com/SeanMBlakley/status/1459971651504852998/photo/3

**Comment by SMB784** [comment]
I have actually tested the Acorn CLE-215+ with the ORICO M2V01-C4, and it reports having a JHL7540 and functions as well as the Avolution enclosure with a JHL6340. See this follow-up Twitter post:
https://mobile.twitter.com/SeanMBlakley/status/1460358170887569408

I haven't verified this, but my understanding is that the JHL7540 has a USB 3.1 fallback sharing the same space on the chip, which would take over in the event that it is not connected to a thunderbolt capable port. While the FPGA would likely remain powered while connected to USB3.1, I doubt it would connect correctly given that it's no longer a PCIe device.

**Comment by mithro** [comment]
FYI - LUNA from @greatscotgadgets is a USB3.0 core for an FPGA using the high speed transceivers (https://luna.readthedocs.io/en/latest/). There is also https://github.com/enjoy-digital/usb3_pipe

**Comment by SMB784** [comment]
The thunderbolt works with the JHL7540 housed in the ORICO M2V01-C4 as shown in the readme file, so I'll close this issue for now. Please feel free to make a new issue if you have any further questions.
